# Site settings
title: Gweek Blog
SEOTitle: 咕咕鸡 | Gweek Blog
header-img: img/home-bg.jpg
email: soslane@duck.com
description: "这里是咕咕鸡的个人博客"
keyword: "Blog,Java,node.js,Linux,Windows,css,html,go,python"
url: "https://igweek.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
weibo_username: soslane
zhihu_username: soslane
github_username: igweek
#twitter_username: soslane
#facebook_username:  soslane
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: gweekchow

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "G-GWLZQST0ED" # Format: UA-xxxxxx-xx
ga_domain: igweek.github.io

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "Fake it till you make it <br> Cloud Computing Team @ Gweek"
sidebar-avatar: https://jsd.cdn.zzko.cn/gh/soslane/picgo@main/path/429.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends:
  [
    { title: "我娇贵的小绝怂", href: "https://bbs.myla.eu.org/" },
    { title: "Gweek", href: "https://gweek.myla.eu.org" },
    { title: "Typecho", href: "https://blog.beybi.eu.org" },
    { title: "Pinbox", href: "https://withpinbox.com/items" },
  ]
